/-
Spectral Stability Across Obstruction Interfaces in Geometric Transport Systems
(Jeromie Beasley, DOI 10.5281/zenodo.20818899): the exact finite results.

The operator is `H_N(ε) = A + D₀ + εE` on `ℝ² ⊗ ℝᴺ`, with `A = α J ⊗ Δ₁` (symplectic `J`,
centered difference `Δ₁`) and `D₀ = diag(B₁, …, B_N)` with symmetric Hessians `B_n`.

* Theorem 3.1: `J` and `Δ₁` are skew, so `A = α J ⊗ Δ₁` is symmetric; hence its spectrum is
  real (it is Hermitian as a real matrix).
* `D₀` is symmetric, so `H_N(0) = A + D₀` is symmetric, hence normal.
* Non-normality is generated only by `εE`: for symmetric `S`,
  `[S + εE, (S + εE)ᵀ] = ε(SEᵀ + ES − SE − EᵀS) + ε²[E, Eᵀ]`, which is `O(ε)`.
* Corollary 9.2's scaling: at contour distance `δ = c√ε` the first-order resolvent correction
  `εΔ/δ²` is `Δ/c²`, independent of `ε`.
* Theorem 11.1: the second difference `(ψ(τ+δ) − 2ψ(τ) + ψ(τ−δ))/δ²` is exact on cubics, and on
  `τ⁴` its error is exactly `δ²/12 · ψ⁗`, the order the theorem states.
-/
import Mathlib

namespace SpectralStability

open Matrix

/-! ## Theorem 3.1: the transport operator is symmetric -/

/-- The internal symplectic matrix. -/
def J : Matrix (Fin 2) (Fin 2) ℝ := !![0, 1; -1, 0]

/-- The centered difference `(Δ₁ψ)_n = ψ_{n+1} − ψ_{n−1}`. -/
def Δ₁ (N : ℕ) : Matrix (Fin N) (Fin N) ℝ :=
  of fun i j => (if j.val = i.val + 1 then 1 else 0) - (if j.val + 1 = i.val then 1 else 0)

theorem J_skew : Jᵀ = -J := by
  ext i j; fin_cases i <;> fin_cases j <;> simp [J]

theorem Δ₁_skew (N : ℕ) : (Δ₁ N)ᵀ = -Δ₁ N := by
  ext i j
  simp only [transpose_apply, Δ₁, of_apply, neg_apply]
  split_ifs <;> omega

/-- **Theorem 3.1.** The product of two skew factors acting on independent indices is
symmetric: `(J ⊗ Δ₁)ᵀ = J ⊗ Δ₁`. -/
theorem transport_symmetric (N : ℕ) (α : ℝ) :
    (α • kroneckerMap (· * ·) J (Δ₁ N))ᵀ = α • kroneckerMap (· * ·) J (Δ₁ N) := by
  rw [transpose_smul, ← kroneckerMap_transpose, J_skew, Δ₁_skew]
  congr 1
  ext ⟨a, b⟩ ⟨c, d⟩
  simp [kroneckerMap_apply]

/-- **Theorem 3.1, the general mechanism.** Two commuting skew matrices have a symmetric
product. -/
theorem skew_commuting_symmetric {n : Type*} [Fintype n] (X Y : Matrix n n ℝ)
    (hX : Xᵀ = -X) (hY : Yᵀ = -Y) (hXY : X * Y = Y * X) : (X * Y)ᵀ = X * Y := by
  rw [transpose_mul, hX, hY, neg_mul_neg, hXY]

/-- **Real spectrum.** The transport operator is Hermitian as a real matrix, so its spectrum is
real. -/
theorem transport_hermitian (N : ℕ) (α : ℝ) :
    (α • kroneckerMap (· * ·) J (Δ₁ N)).IsHermitian := by
  unfold IsHermitian
  rw [conjTranspose_eq_transpose_of_trivial]
  exact transport_symmetric N α

/-- **The obstruction field is symmetric.** `D₀ = diag(B₁, …, B_N)` with `B_nᵀ = B_n`. -/
theorem obstruction_symmetric {N : ℕ} (B : Fin N → Matrix (Fin 2) (Fin 2) ℝ)
    (hB : ∀ n, (B n)ᵀ = B n) : (blockDiagonal B)ᵀ = blockDiagonal B := by
  rw [blockDiagonal_transpose]
  congr 1
  funext n
  exact hB n

/-! ## Non-normality is generated by `εE` alone -/

section Commutator

variable {n : Type*} [Fintype n]

/-- **At `ε = 0` the operator is normal.** A symmetric matrix commutes with its transpose. -/
theorem symmetric_normal (S : Matrix n n ℝ) (hS : Sᵀ = S) : S * Sᵀ - Sᵀ * S = 0 := by
  rw [hS, sub_self]

/-- **The commutator is `O(ε)`.** For symmetric `S`,
`[S + εE, (S + εE)ᵀ] = ε(SEᵀ + ES − SE − EᵀS) + ε²(EEᵀ − EᵀE)`. -/
theorem commutator_expansion (S E : Matrix n n ℝ) (hS : Sᵀ = S) (ε : ℝ) :
    (S + ε • E) * (S + ε • E)ᵀ - (S + ε • E)ᵀ * (S + ε • E) =
      ε • (S * Eᵀ + E * S - S * E - Eᵀ * S) + ε ^ 2 • (E * Eᵀ - Eᵀ * E) := by
  rw [transpose_add, transpose_smul, hS]
  simp only [add_mul, mul_add, smul_mul_assoc, mul_smul_comm, smul_smul, smul_add, smul_sub, sq]
  abel

end Commutator

/-! ## Corollary 9.2: the bulge scaling -/

/-- **Corollary 9.2.** At contour distance `δ = c√ε`, the first-order correction `εΔ/δ²`
equals `Δ/c²`, so the bulge height scales as `√ε · Δ` with no residual `ε`. -/
theorem bulge_scaling (ε c Δ : ℝ) (hε : 0 < ε) (hc : c ≠ 0) :
    ε * Δ / (c * √ε) ^ 2 = Δ / c ^ 2 := by
  rw [mul_pow, Real.sq_sqrt hε.le]
  field_simp

/-! ## Theorem 11.1: the second difference -/

/-- The discrete second difference `(ψ(τ+δ) − 2ψ(τ) + ψ(τ−δ))/δ²`. -/
noncomputable def secondDiff (ψ : ℝ → ℝ) (δ τ : ℝ) : ℝ := (ψ (τ + δ) - 2 * ψ τ + ψ (τ - δ)) / δ ^ 2

/-- **Theorem 11.1, cubics.** The second difference is exact on every cubic:
it returns `ψ'' = 2c₂ + 6c₃τ`. -/
theorem secondDiff_cubic (c0 c1 c2 c3 δ τ : ℝ) (hδ : δ ≠ 0) :
    secondDiff (fun x => c0 + c1 * x + c2 * x ^ 2 + c3 * x ^ 3) δ τ = 2 * c2 + 6 * c3 * τ := by
  unfold secondDiff
  field_simp
  ring

/-- **Theorem 11.1, the error term.** On `ψ = τ⁴` the error is exactly `δ²/12 · ψ⁗ = 2δ²`,
the order `O(δ²)` stated by the theorem. -/
theorem secondDiff_quartic (δ τ : ℝ) (hδ : δ ≠ 0) :
    secondDiff (fun x => x ^ 4) δ τ - 12 * τ ^ 2 = δ ^ 2 / 12 * 24 := by
  unfold secondDiff
  field_simp
  ring

end SpectralStability
